### ISSUE TITLE
Set static IP based on SSID

### ISSUE THREAD

**Issue by mattie47** [NetworkConfiguration/dhcpcd#216] opened 2023-06-26 03:42 UTC
Hi,

There are numerous posts online (typically in the raspberry pi forums) which suggest you can use various configuration under option "ssid".

I can't for the life of me get this working, and I wanted to clarify:
* Is there there something wrong with my configuration?
* Am I misunderstanding what should be possible?

Use case:
I want to be able to set a static IP provided I'm connected to a certain SSID. Otherwise, use DHCP.

The docs state: `ssid - Subsequent options are only parsed for this wireless ssid`

As below, my SSID has a space in it. What's unclear from the docs is:
* Are you supposed to enter the SSID "as is" or do you need to wrap in quotes? 
* The leases file for my interface in ` /var/lib/dhcpcd5/` has `wlan1-My\040Network.lease` the file name like so, so I also tried matching based on this. 

```
 /etc/dhcpcd.conf

<output omitted>

ssid "My Network"
#ssid My\040Network
#ssid "My\040Network"
static ip_address=192.168.1.70/24
static routers=192.168.1.254
static domain_name_servers=192.168.1.254
```

Note, I can successfully set a static IP via dhcpcd provided I specify interface instead of ssid:

```
interface wlan0
static ip_address=192.168.1.70/24
static routers=192.168.1.254
static domain_name_servers=192.168.1.254
```

This is quite unhelpful however if you're taking for example a laptop from work, to home, with one location using a static IP, and the other requiring DHCP.

_why not simply configure an address reservation?_ Because this is not always feasible if for example you don't have control over the DHCP server, but company policy allows user to reserve static IPs (just not through the actual server itself). 

I've been banging my head against a wall for hours trying to make something around this work. 

Help appreciated. 

dhcpcd version - dhcpcd-8.1.2 

Thanks,

Matt

**Comment by rsmarples** [comment] 2023-06-26 10:22
I don't have a wireless interface to hand right now, but does this work?

```
ssid My Network
static ip_address=192.168.1.70/24
static routers=192.168.1.254
static domain_name_servers=192.168.1.254
```

**Comment by mattie47** [comment] 2023-07-26 04:25
I *think* that may have worked in some circumstances (apologies but I had to move on from this issue).

I found trying to apply to wlan1 or another wlan interface that networking had issues i.e. I don't see any ability to also work in conjunction with the interface command.

**Comment by rsmarples** [comment] 2023-11-09 12:54
The interface and ssid blocks have no relation - you cannot tie a ssid to a specific interface.
This is by design.
As you've moved on, closing.

**Closed by rsmarples** 2023-11-09 12:54 UTC
Labels: awaiting feedback
