### ISSUE TITLE
[FR] RFC4191 - Route Information Option

### ISSUE THREAD

**Issue by agowa** [NetworkConfiguration/dhcpcd#177] opened 2023-01-24 06:43 UTC
Edit: RFC4191 is currently not supported. Therefore route information objects are ignored.

routes from a router advertisement aren't configured. Does dhcpcd filter routes? It sets accept_ra to 0, so it would have to handle these routes as well. Do I have a configuration issue here or is this currently a limitation?

Log:
```
Jan 24 05:50:53 [29640]: eth2: Router Advertisement from fe80::d8c4:d2f1:b941:018d
```

radvdump:
```
interface eth2
{
        AdvSendAdvert on;
        # Note: {Min,Max}RtrAdvInterval cannot be obtained with radvdump
        AdvManagedFlag off;
        AdvOtherConfigFlag on;
        AdvReachableTime 0;
        AdvRetransTimer 0;
        AdvCurHopLimit 64;
        AdvDefaultLifetime 0;
        AdvHomeAgentFlag off;
        AdvDefaultPreference medium;
        AdvSourceLLAddress on;

        route 64:ff9b::/96
        {
                AdvRoutePreference medium;
                AdvRouteLifetime 3600;
        }; # End of route definition


        RDNSS 2001:db8:6b2a:69ec:1bfa:03ed:4728:139d
        {
                AdvRDNSSLifetime 10;
        }; # End of RDNSS definition

}; # End of interface definition
```

dhcpcd.conf:
```
debug
logfile /var/log/dhcpcd.log
duid 574f5666-049e-462d-8775-940bf474faed
persistent
vendorclassid
option domain_name_servers, domain_name, domain_search
option classless_static_routes
option interface_mtu
option rapid_commit
require dhcp_server_identifier
slaac private

noipv4
noarp
noipv4ll
ipv6rs
ipv6ra_fork
fqdn both
noalias
nohook 20-resolv.conf

interface bond0
  ipv6only

interface eth2
  waitip
  iaid 1
  ia_pd 2 bond0/0/64/0
```

related sysctl:
```
net.ipv6.conf.eth2.accept_ra_rt_info_max_plen=96
net.ipv6.conf.eth2.accept_ra=0  # set by dhcpcd itself
```

**Comment by agowa338** [comment] 2023-01-25 17:52
The error is somewhere around the inet6_raroutes function in ipv6.c

Additionally, if there is no RDNS option, it only contains routes, but is not the default router, then rap->expired is true for some reason.

So we have two cases for this error now:

1) RA is from a router that is NOT the default router, but has routes and RDNSS, then it passes the expiry check (`rap->expired` is false) but is skipped by `TAILQ_FOREACH(addr, &rap->addrs, next) {` for some reason.
2) RA is from a router that is NOT the default router, but has only routes specified. `rap->expired` is true for some reason.

radvdump of 1st case (see initial post)

radvdump of 2nd case:
```
interface eth2
{
        AdvSendAdvert on;
        # Note: {Min,Max}RtrAdvInterval cannot be obtained with radvdump
        AdvManagedFlag off;
        AdvOtherConfigFlag off;
        AdvReachableTime 0;
        AdvRetransTimer 0;
        AdvCurHopLimit 64;
        AdvDefaultLifetime 0;
        AdvHomeAgentFlag off;
        AdvDefaultPreference medium;
        AdvSourceLLAddress on;

        route fd64:1e40:1f60:a60b::/64
        {
                AdvRoutePreference medium;
                AdvRouteLifetime 3600;
        }; # End of route definition


        route fd64:1e40:1f60:a60c::/64
        {
                AdvRoutePreference medium;
                AdvRouteLifetime 3600;
        }; # End of route definition

}; # End of interface definition
```

**Comment by agowa338** [comment] 2023-01-25 23:45
After studying the codebase a bit more, the best location to fix this (or implement, as it looks like RFC4191 was never implemented at all) is within https://github.com/NetworkConfiguration/dhcpcd/blob/master/src/ipv6nd.c#L1315

**Comment by cfilipem** [comment] 2023-01-27 10:22
Duplicate of #102

**Comment by rsmarples** [comment] 2023-12-10 10:22
Yes, duplicate.

**Closed by rsmarples** 2023-12-10 10:22 UTC
