### ISSUE TITLE
dhcpcd fails to dump lease info

### ISSUE THREAD

**Issue by Perlovka** [NetworkConfiguration/dhcpcd#69] opened 2021-11-08 05:45 UTC
Hi, v9.4.1 fails to read lease info (9.4.0 not affected):
```
# dhcpcd -U wan 
reason=CARRIER
interface=wan
protocol=link
if_configured=true
ifcarrier=up
ifmetric=4
ifwireless=0
ifflags=69699
ifmtu=1500
skip_hooks=ntp.conf yp.conf resolv.conf

dhcpcd_readdump1: Invalid argument
```

**Comment by rsmarples** [comment] 2021-11-12 11:25
I can't replicate this on NetBSD or Linux and this part of dhcpcd hasn't changed from the prior release.
Can you give me any information about the type of system you are running please?
Can you also check syslog to see if there is any seccomp audit that's failing?

**Comment by Perlovka** [comment] 2021-11-12 12:17
The system is Gentoo ~amd64
```
net-misc/dhcpcd-9.4.1::gentoo  USE="embedded ipv6 udev -debug -privsep"
```
The only log I see is:
```
Nov 12 14:02:47 jupiter dhcpcd[7529]: control command: dhcpcd -U br0
Nov 12 14:02:47 jupiter dhcpcd[7529]: control_free: No such file or directory
Nov 12 14:02:47 jupiter dhcpcd[8002]: dhcpcd_readdump1: Invalid argument
```
With 9.4.0 only first line is written to log and lease dump is success.

**Comment by Perlovka** [comment] 2021-11-12 12:29
Straces, if this could help:
9.4.0:
```
execve("/sbin/dhcpcd", ["dhcpcd", "-U", "br0"], 0x7ffded8ce840 /* 60 vars */) = 0
brk(NULL)                               = 0x555d59afa000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=183093, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 183093, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f6b8f3b3000
close(3)                                = 0
openat(AT_FDCWD, "/lib64/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0 \21\0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=18488, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f6b8f3b1000
mmap(NULL, 20720, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f6b8f3ab000
mmap(0x7f6b8f3ac000, 8192, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1000) = 0x7f6b8f3ac000
mmap(0x7f6b8f3ae000, 4096, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x3000) = 0x7f6b8f3ae000
mmap(0x7f6b8f3af000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x3000) = 0x7f6b8f3af000
close(3)                                = 0
openat(AT_FDCWD, "/lib64/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0@9\2\0\0\0\0\0"..., 832) = 832
pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 784, 64) = 784
pread64(3, "\4\0\0\0 \0\0\0\5\0\0\0GNU\0\1\0\1\300\4\0\0\0;\0\0\0\0\0\0\0"..., 48, 848) = 48
pread64(3, "\4\0\0\0\20\0\0\0\1\0\0\0GNU\0\0\0\0\0\3\0\0\0\2\0\0\0\0\0\0\0", 32, 896) = 32
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=1790112, ...}, AT_EMPTY_PATH) = 0
pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 784, 64) = 784
mmap(NULL, 1803016, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f6b8f1f2000
mmap(0x7f6b8f214000, 1318912, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x22000) = 0x7f6b8f214000
mmap(0x7f6b8f356000, 307200, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x164000) = 0x7f6b8f356000
mmap(0x7f6b8f3a1000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1ae000) = 0x7f6b8f3a1000
mmap(0x7f6b8f3a7000, 13064, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f6b8f3a7000
close(3)                                = 0
mmap(NULL, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f6b8f1ef000
arch_prctl(ARCH_SET_FS, 0x7f6b8f1ef740) = 0
mprotect(0x7f6b8f3a1000, 16384, PROT_READ) = 0
mprotect(0x7f6b8f3af000, 4096, PROT_READ) = 0
mprotect(0x555d58686000, 8192, PROT_READ) = 0
mprotect(0x7f6b8f40f000, 8192, PROT_READ) = 0
munmap(0x7f6b8f3b3000, 183093)          = 0
brk(NULL)                               = 0x555d59afa000
brk(0x555d59b1b000)                     = 0x555d59b1b000
fcntl(0, F_GETFD)                       = 0
fcntl(1, F_GETFD)                       = 0
fcntl(2, F_GETFD)                       = 0
openat(AT_FDCWD, "/etc/localtime", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=2388, ...}, AT_EMPTY_PATH) = 0
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=2388, ...}, AT_EMPTY_PATH) = 0
read(3, "TZif3\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\t\0\0\0\t\0\0\0\0"..., 4096) = 2388
lseek(3, -1506, SEEK_CUR)               = 882
read(3, "TZif3\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\t\0\0\0\t\0\0\0\0"..., 4096) = 1506
close(3)                                = 0
readlink("/proc/self/exe", "/sbin/dhcpcd", 4097) = 12
socket(AF_INET, SOCK_DGRAM, IPPROTO_IP) = 3
close(3)                                = 0
socket(AF_INET6, SOCK_DGRAM, IPPROTO_IP) = 3
close(3)                                = 0
brk(0x555d59b3c000)                     = 0x555d59b3c000
openat(AT_FDCWD, "/etc/dhcpcd.conf", O_RDONLY) = 3
read(3, "# A sample configuration for dhc"..., 65536) = 1429
close(3)                                = 0
newfstatat(AT_FDCWD, "/etc/dhcpcd.conf", {st_mode=S_IFREG|0644, st_size=1429, ...}, 0) = 0
chdir("/")                              = 0
rt_sigaction(SIGPIPE, {sa_handler=SIG_IGN, sa_mask=[PIPE], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f6b8f22a670}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigprocmask(SIG_SETMASK, [HUP INT USR1 USR2 ALRM TERM CHLD], [], 8) = 0
rt_sigaction(SIGTERM, {sa_handler=0x555d58642fd0, sa_mask=[], sa_flags=SA_RESTORER|SA_SIGINFO, sa_restorer=0x7f6b8f22a670}, NULL, 8) = 0
rt_sigaction(SIGINT, {sa_handler=0x555d58642fd0, sa_mask=[], sa_flags=SA_RESTORER|SA_SIGINFO, sa_restorer=0x7f6b8f22a670}, NULL, 8) = 0
rt_sigaction(SIGALRM, {sa_handler=0x555d58642fd0, sa_mask=[], sa_flags=SA_RESTORER|SA_SIGINFO, sa_restorer=0x7f6b8f22a670}, NULL, 8) = 0
rt_sigaction(SIGHUP, {sa_handler=0x555d58642fd0, sa_mask=[], sa_flags=SA_RESTORER|SA_SIGINFO, sa_restorer=0x7f6b8f22a670}, NULL, 8) = 0
rt_sigaction(SIGUSR1, {sa_handler=0x555d58642fd0, sa_mask=[], sa_flags=SA_RESTORER|SA_SIGINFO, sa_restorer=0x7f6b8f22a670}, NULL, 8) = 0
rt_sigaction(SIGUSR2, {sa_handler=0x555d58642fd0, sa_mask=[], sa_flags=SA_RESTORER|SA_SIGINFO, sa_restorer=0x7f6b8f22a670}, NULL, 8) = 0
rt_sigaction(SIGCHLD, {sa_handler=0x555d58642fd0, sa_mask=[], sa_flags=SA_RESTORER|SA_SIGINFO, sa_restorer=0x7f6b8f22a670}, NULL, 8) = 0
ioctl(0, FIONREAD, [0])                 = 0
socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 3
connect(3, {sa_family=AF_UNIX, sun_path="/run/dhcpcd/br0.unpriv.sock"}, 29) = 0
write(3, "dhcpcd\0-U\0br0\0", 14)       = 14
ppoll([{fd=3, events=POLLIN}], 1, {tv_sec=4, tv_nsec=999999662}, [], 8) = 1 ([{fd=3, revents=POLLIN}], left {tv_sec=4, tv_nsec=999998885})
read(3, "\2\0\0\0\0\0\0\0", 8)          = 8
ppoll([{fd=3, events=POLLIN}], 1, {tv_sec=4, tv_nsec=999957824}, [], 8) = 1 ([{fd=3, revents=POLLIN}], left {tv_sec=4, tv_nsec=999957265})
read(3, "}\0\0\0\0\0\0\0", 8)           = 8
ppoll([{fd=3, events=POLLIN}], 1, {tv_sec=4, tv_nsec=999922288}, [], 8) = 1 ([{fd=3, revents=POLLIN}], left {tv_sec=4, tv_nsec=999921869})
read(3, "reason=CARRIER\0interface=br0\0pro"..., 125) = 125
newfstatat(1, "", {st_mode=S_IFCHR|0620, st_rdev=makedev(0x88, 0), ...}, AT_EMPTY_PATH) = 0
write(1, "reason=CARRIER\n", 15reason=CARRIER
)        = 15
write(1, "interface=br0\n", 14interface=br0
)         = 14
write(1, "protocol=link\n", 14protocol=link
)         = 14
write(1, "if_configured=true\n", 19if_configured=true
)    = 19
write(1, "ifcarrier=up\n", 13ifcarrier=up
)          = 13
write(1, "ifmetric=10\n", 12ifmetric=10
)           = 12
write(1, "ifwireless=0\n", 13ifwireless=0
)          = 13
write(1, "ifflags=69955\n", 14ifflags=69955
)         = 14
write(1, "ifmtu=1500\n", 11ifmtu=1500
)            = 11
write(1, "\n", 1
)                       = 1
ppoll([{fd=3, events=POLLIN}], 1, {tv_sec=4, tv_nsec=999701840}, [], 8) = 1 ([{fd=3, revents=POLLIN}], left {tv_sec=4, tv_nsec=999701106})
read(3, "]\1\0\0\0\0\0\0", 8)           = 8
ppoll([{fd=3, events=POLLIN}], 1, {tv_sec=4, tv_nsec=999667851}, [], 8) = 1 ([{fd=3, revents=POLLIN}], left {tv_sec=4, tv_nsec=999667429})
read(3, "reason=BOUND\0interface=br0\0proto"..., 349) = 349
write(1, "reason=BOUND\n", 13reason=BOUND
)          = 13
write(1, "interface=br0\n", 14interface=br0
)         = 14
write(1, "protocol=dhcp\n", 14protocol=dhcp
)         = 14
write(1, "ip_address=10.0.0.2\n", 20ip_address=10.0.0.2
)   = 20
write(1, "subnet_cidr=24\n", 15subnet_cidr=24
)        = 15
write(1, "network_number=10.0.0.0\n", 24network_number=10.0.0.0
) = 24
write(1, "subnet_mask=255.255.255.0\n", 26subnet_mask=255.255.255.0
) = 26
write(1, "routers=10.0.0.1\n", 17routers=10.0.0.1
)      = 17
write(1, "domain_name_servers=10.0.0.1\n", 29domain_name_servers=10.0.0.1
) = 29
write(1, "domain_name=perlovka.net\n", 25domain_name=perlovka.net
) = 25
write(1, "broadcast_address=10.0.0.255\n", 29broadcast_address=10.0.0.255
) = 29
write(1, "dhcp_lease_time=4294967295\n", 27dhcp_lease_time=4294967295
) = 27
write(1, "dhcp_message_type=5\n", 20dhcp_message_type=5
)   = 20
write(1, "dhcp_server_identifier=10.0.0.1\n", 32dhcp_server_identifier=10.0.0.1
) = 32
shutdown(3, SHUT_RDWR)                  = 0
close(3)                                = 0
unlink("")                              = -1 ENOENT (No such file or directory)
brk(0x555d59b3b000)                     = 0x555d59b3b000
exit_group(0)                           = ?
+++ exited with 0 +++
```
9.4.1:
```
execve("/sbin/dhcpcd", ["dhcpcd", "-U", "br0"], 0x7fff16870a70 /* 60 vars */) = 0
brk(NULL)                               = 0x55bffd3d4000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=183093, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 183093, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fa2a3971000
close(3)                                = 0
openat(AT_FDCWD, "/lib64/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0 \21\0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=18488, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fa2a396f000
mmap(NULL, 20720, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fa2a3969000
mmap(0x7fa2a396a000, 8192, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1000) = 0x7fa2a396a000
mmap(0x7fa2a396c000, 4096, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x3000) = 0x7fa2a396c000
mmap(0x7fa2a396d000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x3000) = 0x7fa2a396d000
close(3)                                = 0
openat(AT_FDCWD, "/lib64/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0@9\2\0\0\0\0\0"..., 832) = 832
pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 784, 64) = 784
pread64(3, "\4\0\0\0 \0\0\0\5\0\0\0GNU\0\1\0\1\300\4\0\0\0;\0\0\0\0\0\0\0"..., 48, 848) = 48
pread64(3, "\4\0\0\0\20\0\0\0\1\0\0\0GNU\0\0\0\0\0\3\0\0\0\2\0\0\0\0\0\0\0", 32, 896) = 32
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=1790112, ...}, AT_EMPTY_PATH) = 0
pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 784, 64) = 784
mmap(NULL, 1803016, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fa2a37b0000
mmap(0x7fa2a37d2000, 1318912, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x22000) = 0x7fa2a37d2000
mmap(0x7fa2a3914000, 307200, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x164000) = 0x7fa2a3914000
mmap(0x7fa2a395f000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1ae000) = 0x7fa2a395f000
mmap(0x7fa2a3965000, 13064, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fa2a3965000
close(3)                                = 0
mmap(NULL, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fa2a37ad000
arch_prctl(ARCH_SET_FS, 0x7fa2a37ad740) = 0
mprotect(0x7fa2a395f000, 16384, PROT_READ) = 0
mprotect(0x7fa2a396d000, 4096, PROT_READ) = 0
mprotect(0x55bffbe64000, 8192, PROT_READ) = 0
mprotect(0x7fa2a39cd000, 8192, PROT_READ) = 0
munmap(0x7fa2a3971000, 183093)          = 0
brk(NULL)                               = 0x55bffd3d4000
brk(0x55bffd3f5000)                     = 0x55bffd3f5000
fcntl(0, F_GETFD)                       = 0
fcntl(1, F_GETFD)                       = 0
fcntl(2, F_GETFD)                       = 0
openat(AT_FDCWD, "/etc/localtime", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=2388, ...}, AT_EMPTY_PATH) = 0
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=2388, ...}, AT_EMPTY_PATH) = 0
read(3, "TZif3\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\t\0\0\0\t\0\0\0\0"..., 4096) = 2388
lseek(3, -1506, SEEK_CUR)               = 882
read(3, "TZif3\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\t\0\0\0\t\0\0\0\0"..., 4096) = 1506
close(3)                                = 0
readlink("/proc/self/exe", "/sbin/dhcpcd", 4097) = 12
socket(AF_INET, SOCK_DGRAM, IPPROTO_IP) = 3
close(3)                                = 0
socket(AF_INET6, SOCK_DGRAM, IPPROTO_IP) = 3
close(3)                                = 0
brk(0x55bffd416000)                     = 0x55bffd416000
openat(AT_FDCWD, "/etc/dhcpcd.conf", O_RDONLY) = 3
read(3, "# A sample configuration for dhc"..., 65536) = 1429
close(3)                                = 0
newfstatat(AT_FDCWD, "/etc/dhcpcd.conf", {st_mode=S_IFREG|0644, st_size=1429, ...}, 0) = 0
chdir("/")                              = 0
rt_sigaction(SIGPIPE, {sa_handler=SIG_IGN, sa_mask=[PIPE], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fa2a37e8670}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigprocmask(SIG_SETMASK, [HUP INT USR1 USR2 ALRM TERM CHLD], [], 8) = 0
rt_sigaction(SIGTERM, {sa_handler=0x55bffbe20ff0, sa_mask=[], sa_flags=SA_RESTORER|SA_SIGINFO, sa_restorer=0x7fa2a37e8670}, NULL, 8) = 0
rt_sigaction(SIGINT, {sa_handler=0x55bffbe20ff0, sa_mask=[], sa_flags=SA_RESTORER|SA_SIGINFO, sa_restorer=0x7fa2a37e8670}, NULL, 8) = 0
rt_sigaction(SIGALRM, {sa_handler=0x55bffbe20ff0, sa_mask=[], sa_flags=SA_RESTORER|SA_SIGINFO, sa_restorer=0x7fa2a37e8670}, NULL, 8) = 0
rt_sigaction(SIGHUP, {sa_handler=0x55bffbe20ff0, sa_mask=[], sa_flags=SA_RESTORER|SA_SIGINFO, sa_restorer=0x7fa2a37e8670}, NULL, 8) = 0
rt_sigaction(SIGUSR1, {sa_handler=0x55bffbe20ff0, sa_mask=[], sa_flags=SA_RESTORER|SA_SIGINFO, sa_restorer=0x7fa2a37e8670}, NULL, 8) = 0
rt_sigaction(SIGUSR2, {sa_handler=0x55bffbe20ff0, sa_mask=[], sa_flags=SA_RESTORER|SA_SIGINFO, sa_restorer=0x7fa2a37e8670}, NULL, 8) = 0
rt_sigaction(SIGCHLD, {sa_handler=0x55bffbe20ff0, sa_mask=[], sa_flags=SA_RESTORER|SA_SIGINFO, sa_restorer=0x7fa2a37e8670}, NULL, 8) = 0
ioctl(0, FIONREAD, [0])                 = 0
socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 3
connect(3, {sa_family=AF_UNIX, sun_path="/run/dhcpcd/br0.unpriv.sock"}, 29) = 0
write(3, "dhcpcd\0-U\0br0\0", 14)       = 14
ppoll([{fd=3, events=POLLIN}], 1, {tv_sec=4, tv_nsec=999999675}, [], 8) = 1 ([{fd=3, revents=POLLIN}], left {tv_sec=4, tv_nsec=999998951})
read(3, "\2\0\0\0\0\0\0\0", 8)          = 8
ppoll([{fd=3, events=POLLIN}], 1, {tv_sec=4, tv_nsec=999949806}, [], 8) = 1 ([{fd=3, revents=POLLIN|POLLHUP}], left {tv_sec=4, tv_nsec=999948728})
read(3, "|\0\0\0\0\0\0\0", 8)           = 8
ppoll([{fd=3, events=POLLIN}], 1, {tv_sec=4, tv_nsec=999907938}, [], 8) = 1 ([{fd=3, revents=POLLIN|POLLHUP}], left {tv_sec=4, tv_nsec=999907501})
read(3, "reason=CARRIER\0interface=br0\0pro"..., 124) = 124
newfstatat(1, "", {st_mode=S_IFCHR|0620, st_rdev=makedev(0x88, 0), ...}, AT_EMPTY_PATH) = 0
write(1, "reason=CARRIER\n", 15reason=CARRIER
)        = 15
write(1, "interface=br0\n", 14interface=br0
)         = 14
write(1, "protocol=link\n", 14protocol=link
)         = 14
write(1, "if_configured=true\n", 19if_configured=true
)    = 19
write(1, "ifcarrier=up\n", 13ifcarrier=up
)          = 13
write(1, "ifmetric=9\n", 11ifmetric=9
)            = 11
write(1, "ifwireless=0\n", 13ifwireless=0
)          = 13
write(1, "ifflags=69955\n", 14ifflags=69955
)         = 14
write(1, "ifmtu=1500\n", 11ifmtu=1500
)            = 11
write(1, "\n", 1
)                       = 1
ppoll([{fd=3, events=POLLIN}], 1, {tv_sec=4, tv_nsec=999652922}, [], 8) = 1 ([{fd=3, revents=POLLIN|POLLHUP}], left {tv_sec=4, tv_nsec=999652400})
read(3, "", 8)                          = 0
write(2, "dhcpcd_readdump1: Invalid argume"..., 35dhcpcd_readdump1: Invalid argument
) = 35
getpid()                                = 15624
socket(AF_UNIX, SOCK_DGRAM|SOCK_CLOEXEC, 0) = 4
connect(4, {sa_family=AF_UNIX, sun_path="/dev/log"}, 110) = 0
sendto(4, "<27>Nov 12 14:23:15 dhcpcd[15624"..., 69, MSG_NOSIGNAL, NULL, 0) = 69
close(3)                                = 0
unlink("")                              = -1 ENOENT (No such file or directory)
close(4)                                = 0
exit_group(1)                           = ?
+++ exited with 1 +++
```

**Comment by rsmarples** [comment] 2021-11-12 12:34
Based on your log snippet

```
Nov 12 14:02:47 jupiter dhcpcd[7529]: control command: dhcpcd -U br0
Nov 12 14:02:47 jupiter dhcpcd[7529]: control_free: No such file or directory
Nov 12 14:02:47 jupiter dhcpcd[8002]: dhcpcd_readdump1: Invalid argument
```

I suspect the issue is with the running dhcpcd process and not the client reporting the problem. See the control_free error - I suspect that the communication was terminated early to the client and thus explains the error reported.

**Comment by rsmarples** [comment] 2021-11-12 14:47
The control error infact looks bogus - the fd not being in use is not an error when freeing.
I removed that diagnostic in 886313867619977810c275cf33e913baa5124c05.

Could you post the output of this please? `dhcpcd --version`
That allows me to see how dhcpcd is compiled on your platform.

**Comment by Perlovka** [comment] 2021-11-12 15:06
Sure,
```
dhcpcd 9.4.1
Copyright (c) 2006-2021 Roy Marples
Compiled in features: INET ARP ARPing IPv4LL INET6 DHCPv6 AUTH
```

**Comment by rsmarples** [comment] 2021-11-12 15:12
Replicated on the dhcpcd-9 branch only for non privsep builds.

**Comment by rsmarples** [comment] 2021-11-12 16:28
This should be fixed in 2b4fe4c12b5d4366ff21fabf3a6c3799f8e4fa53. Can you test it please?

**Comment by Perlovka** [comment] 2021-11-13 13:06
Thanks! Works for me )

**Closed** 2021-11-13 13:52 UTC

**Comment by staticglobal** [comment] 2023-03-02 00:03
I'm happy to see a fix for this issue was merged more than 15 months ago... however no new releases have been published since then. 9.4.1 is still the latest version and has this bug. Please publish a new release soon that contains this fix.
